package core;

public enum EventType {
    MOTION_DETECTED,
    LIGHT_LEVEL_CHANGED,
    TEMPERATURE_CHANGED,
    ENERGY_CONSUMPTION_CHANGED,
    VOICE_COMMAND_RECEIVED,
    REMOTE_COMMAND_RECEIVED
}
